"""
Notification Center: shows overdue-activity / upcoming-transfer alerts
generated by NotificationController.
"""
from __future__ import annotations

from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QListWidget, QListWidgetItem,
    QPushButton, QLabel,
)

LEVEL_ICON = {"info": "ℹ️", "warning": "⚠️", "critical": "🛑"}


class NotificationCenterDialog(QDialog):
    def __init__(self, controller, parent=None):
        super().__init__(parent)
        self.controller = controller
        self.setWindowTitle("Notification Center")
        self.setMinimumSize(480, 420)

        layout = QVBoxLayout(self)
        header = QHBoxLayout()
        header.addWidget(QLabel("<b>Overdue & Upcoming Alerts</b>"))
        header.addStretch()
        mark_all_btn = QPushButton("Mark all read")
        mark_all_btn.setObjectName("SecondaryButton")
        mark_all_btn.clicked.connect(self._mark_all_read)
        clear_btn = QPushButton("Clear all")
        clear_btn.setObjectName("DangerButton")
        clear_btn.clicked.connect(self._clear_all)
        header.addWidget(mark_all_btn)
        header.addWidget(clear_btn)
        layout.addLayout(header)

        self.list = QListWidget()
        layout.addWidget(self.list)

        close_btn = QPushButton("Close")
        close_btn.clicked.connect(self.accept)
        layout.addWidget(close_btn)

        self._reload()

    def _reload(self):
        self.list.clear()
        notes = self.controller.list_all()
        if not notes:
            self.list.addItem("No notifications. Everything is on track. ✅")
            return
        for note in notes:
            icon = LEVEL_ICON.get(note.level, "ℹ️")
            prefix = "" if note.is_read else "🔵 "
            item = QListWidgetItem(f"{prefix}{icon} {note.message}  "
                                    f"({note.created_at.strftime('%Y-%m-%d %H:%M')})")
            self.list.addItem(item)

    def _mark_all_read(self):
        self.controller.mark_all_read()
        self._reload()

    def _clear_all(self):
        self.controller.clear_all()
        self._reload()
